# SPDX-FileCopyrightText: 2024 Dogan Ulus <dogan.ulus@bogazici.edu.tr>
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
  "containers/**",
  "kubes/**",
  "README.md",
  ".devcontainer/**",
  ".github/**"
]
SPDX-FileCopyrightText = ["2024 Dogan Ulus <dogan.ulus@bogazici.edu.tr>"]
SPDX-License-Identifier = "Apache-2.0"

